// packages/examples/vue3/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'
import imgUrl from './assets/vue.svg'
</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img aria-label="logo-assets" src="/shared/images/vite.svg"
           alt="Vite logo"/>
      <img aria-label="img-base" src="/images/settings.png"/>
      <img aria-label="img-base-with-parent" src="/public2/images/settings.png"
           alt="Vite logo"/>
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img :src="imgUrl" class="logo vue" alt="Vue logo"/>
    </a>
  </div>
  <HelloWorld msg="Vite + Vue"/>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// examples/react/src/App.tsx
import {useState} from 'react'
import reactLogo from './assets/react.svg'
// import viteLogo from '/vite.svg'
import './App.css'

function App() {
    const [count, setCount] = useState(0)

    return (
        <>
            <div>
                <a href="https://vitejs.dev" target="_blank">
                    <img aria-label={"logo-assets"} src={"/base/shared/images/vite.svg"} className="logo"
                         alt="Vite logo"/>
                    <img aria-label={"img-output-subfolder"} src={"/base/shared/images/sub-folder/sub-image.png"}
                         className="logo"
                         alt="Vite logo"/>
                    <img aria-label={"img-output-nested-subfolder"}
                         src={"/base/shared/images/sub-folder/nested-sub-folder/sub-image1.png"}
                         className="logo"
                         alt="Vite logo"/>
                    <img aria-label={"img-base"} src={"/base/images/settings.png"} className="logo" alt="Vite logo"/>

                    <img aria-label={"img-base-with-parent"} src={"/base/public2/images/settings.png"} className="logo"
                         alt="Vite logo"/>
                    <img aria-label={"logo-assets-symlink"} src={"/base/shared/images/change1.png"} className="logo"
                         alt="Vite logo"/>
                </a>
                <a href="https://react.dev" target="_blank">
                    <img src={reactLogo} className="logo react" alt="React logo"/>
                </a>
            </div>
            <h1>Vite + React</h1>
            <div className="card">
                <button onClick={() => setCount((count) => count + 1)}>
                    count is {count}
                </button>
                <p>
                    Edit <code>src/App.tsx</code> and save to test HMR
                </p>
            </div>
            <p className="read-the-docs">
                Click on the Vite and React logos to learn more
            </p>
        </>
    )
}

export default App
